/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as LocalRouteImport } from './routes/local'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalIndexRouteImport } from './routes/local.index'
import { Route as WWorkspaceIdRouteImport } from './routes/w.$workspaceId'
import { Route as LocalChannelIdRouteImport } from './routes/local.$channelId'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as ConnectTokenRouteImport } from './routes/connect.$token'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w.$workspaceId.index'
import { Route as WWorkspaceIdInboxRouteImport } from './routes/w.$workspaceId.inbox'
import { Route as WWorkspaceIdEventsRouteImport } from './routes/w.$workspaceId.events'
import { Route as WWorkspaceIdChannelSlugRouteImport } from './routes/w.$workspaceId.$channelSlug'
import { Route as WWorkspaceIdTThreadIdRouteImport } from './routes/w.$workspaceId.t.$threadId'
import { Route as WWorkspaceIdDChannelIdRouteImport } from './routes/w.$workspaceId.d.$channelId'
import { Route as WWorkspaceIdCChannelIdRouteImport } from './routes/w.$workspaceId.c.$channelId'
import { Route as WWorkspaceIdGGroupSlugChannelSlugRouteImport } from './routes/w.$workspaceId.g.$groupSlug.$channelSlug'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIndexRoute = LocalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalRoute,
} as any)
const WWorkspaceIdRoute = WWorkspaceIdRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalChannelIdRoute = LocalChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => LocalRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTokenRoute = ConnectTokenRouteImport.update({
  id: '/connect/$token',
  path: '/connect/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdInboxRoute = WWorkspaceIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdEventsRoute = WWorkspaceIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdChannelSlugRoute = WWorkspaceIdChannelSlugRouteImport.update({
  id: '/$channelSlug',
  path: '/$channelSlug',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdTThreadIdRoute = WWorkspaceIdTThreadIdRouteImport.update({
  id: '/t/$threadId',
  path: '/t/$threadId',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdDChannelIdRoute = WWorkspaceIdDChannelIdRouteImport.update({
  id: '/d/$channelId',
  path: '/d/$channelId',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdCChannelIdRoute = WWorkspaceIdCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdGGroupSlugChannelSlugRoute =
  WWorkspaceIdGGroupSlugChannelSlugRouteImport.update({
    id: '/g/$groupSlug/$channelSlug',
    path: '/g/$groupSlug/$channelSlug',
    getParentRoute: () => WWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/docs': typeof DocsRoute
  '/local': typeof LocalRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/connect/$token': typeof ConnectTokenRoute
  '/invite/$code': typeof InviteCodeRoute
  '/local/$channelId': typeof LocalChannelIdRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/local/': typeof LocalIndexRoute
  '/w/$workspaceId/$channelSlug': typeof WWorkspaceIdChannelSlugRoute
  '/w/$workspaceId/events': typeof WWorkspaceIdEventsRoute
  '/w/$workspaceId/inbox': typeof WWorkspaceIdInboxRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof WWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$channelId': typeof WWorkspaceIdDChannelIdRoute
  '/w/$workspaceId/t/$threadId': typeof WWorkspaceIdTThreadIdRoute
  '/w/$workspaceId/g/$groupSlug/$channelSlug': typeof WWorkspaceIdGGroupSlugChannelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/docs': typeof DocsRoute
  '/workspaces': typeof WorkspacesRoute
  '/connect/$token': typeof ConnectTokenRoute
  '/invite/$code': typeof InviteCodeRoute
  '/local/$channelId': typeof LocalChannelIdRoute
  '/local': typeof LocalIndexRoute
  '/w/$workspaceId/$channelSlug': typeof WWorkspaceIdChannelSlugRoute
  '/w/$workspaceId/events': typeof WWorkspaceIdEventsRoute
  '/w/$workspaceId/inbox': typeof WWorkspaceIdInboxRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof WWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$channelId': typeof WWorkspaceIdDChannelIdRoute
  '/w/$workspaceId/t/$threadId': typeof WWorkspaceIdTThreadIdRoute
  '/w/$workspaceId/g/$groupSlug/$channelSlug': typeof WWorkspaceIdGGroupSlugChannelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/docs': typeof DocsRoute
  '/local': typeof LocalRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/connect/$token': typeof ConnectTokenRoute
  '/invite/$code': typeof InviteCodeRoute
  '/local/$channelId': typeof LocalChannelIdRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/local/': typeof LocalIndexRoute
  '/w/$workspaceId/$channelSlug': typeof WWorkspaceIdChannelSlugRoute
  '/w/$workspaceId/events': typeof WWorkspaceIdEventsRoute
  '/w/$workspaceId/inbox': typeof WWorkspaceIdInboxRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof WWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$channelId': typeof WWorkspaceIdDChannelIdRoute
  '/w/$workspaceId/t/$threadId': typeof WWorkspaceIdTThreadIdRoute
  '/w/$workspaceId/g/$groupSlug/$channelSlug': typeof WWorkspaceIdGGroupSlugChannelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/docs'
    | '/local'
    | '/workspaces'
    | '/connect/$token'
    | '/invite/$code'
    | '/local/$channelId'
    | '/w/$workspaceId'
    | '/local/'
    | '/w/$workspaceId/$channelSlug'
    | '/w/$workspaceId/events'
    | '/w/$workspaceId/inbox'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$channelId'
    | '/w/$workspaceId/t/$threadId'
    | '/w/$workspaceId/g/$groupSlug/$channelSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/docs'
    | '/workspaces'
    | '/connect/$token'
    | '/invite/$code'
    | '/local/$channelId'
    | '/local'
    | '/w/$workspaceId/$channelSlug'
    | '/w/$workspaceId/events'
    | '/w/$workspaceId/inbox'
    | '/w/$workspaceId'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$channelId'
    | '/w/$workspaceId/t/$threadId'
    | '/w/$workspaceId/g/$groupSlug/$channelSlug'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/docs'
    | '/local'
    | '/workspaces'
    | '/connect/$token'
    | '/invite/$code'
    | '/local/$channelId'
    | '/w/$workspaceId'
    | '/local/'
    | '/w/$workspaceId/$channelSlug'
    | '/w/$workspaceId/events'
    | '/w/$workspaceId/inbox'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$channelId'
    | '/w/$workspaceId/t/$threadId'
    | '/w/$workspaceId/g/$groupSlug/$channelSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DocsRoute: typeof DocsRoute
  LocalRoute: typeof LocalRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRoute
  ConnectTokenRoute: typeof ConnectTokenRoute
  InviteCodeRoute: typeof InviteCodeRoute
  WWorkspaceIdRoute: typeof WWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/': {
      id: '/local/'
      path: '/'
      fullPath: '/local/'
      preLoaderRoute: typeof LocalIndexRouteImport
      parentRoute: typeof LocalRoute
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$channelId': {
      id: '/local/$channelId'
      path: '/$channelId'
      fullPath: '/local/$channelId'
      preLoaderRoute: typeof LocalChannelIdRouteImport
      parentRoute: typeof LocalRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$token': {
      id: '/connect/$token'
      path: '/connect/$token'
      fullPath: '/connect/$token'
      preLoaderRoute: typeof ConnectTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/inbox': {
      id: '/w/$workspaceId/inbox'
      path: '/inbox'
      fullPath: '/w/$workspaceId/inbox'
      preLoaderRoute: typeof WWorkspaceIdInboxRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/events': {
      id: '/w/$workspaceId/events'
      path: '/events'
      fullPath: '/w/$workspaceId/events'
      preLoaderRoute: typeof WWorkspaceIdEventsRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/$channelSlug': {
      id: '/w/$workspaceId/$channelSlug'
      path: '/$channelSlug'
      fullPath: '/w/$workspaceId/$channelSlug'
      preLoaderRoute: typeof WWorkspaceIdChannelSlugRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/t/$threadId': {
      id: '/w/$workspaceId/t/$threadId'
      path: '/t/$threadId'
      fullPath: '/w/$workspaceId/t/$threadId'
      preLoaderRoute: typeof WWorkspaceIdTThreadIdRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/d/$channelId': {
      id: '/w/$workspaceId/d/$channelId'
      path: '/d/$channelId'
      fullPath: '/w/$workspaceId/d/$channelId'
      preLoaderRoute: typeof WWorkspaceIdDChannelIdRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/c/$channelId': {
      id: '/w/$workspaceId/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/w/$workspaceId/c/$channelId'
      preLoaderRoute: typeof WWorkspaceIdCChannelIdRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/g/$groupSlug/$channelSlug': {
      id: '/w/$workspaceId/g/$groupSlug/$channelSlug'
      path: '/g/$groupSlug/$channelSlug'
      fullPath: '/w/$workspaceId/g/$groupSlug/$channelSlug'
      preLoaderRoute: typeof WWorkspaceIdGGroupSlugChannelSlugRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
  }
}

interface LocalRouteChildren {
  LocalChannelIdRoute: typeof LocalChannelIdRoute
  LocalIndexRoute: typeof LocalIndexRoute
}

const LocalRouteChildren: LocalRouteChildren = {
  LocalChannelIdRoute: LocalChannelIdRoute,
  LocalIndexRoute: LocalIndexRoute,
}

const LocalRouteWithChildren = LocalRoute._addFileChildren(LocalRouteChildren)

interface WWorkspaceIdRouteChildren {
  WWorkspaceIdChannelSlugRoute: typeof WWorkspaceIdChannelSlugRoute
  WWorkspaceIdEventsRoute: typeof WWorkspaceIdEventsRoute
  WWorkspaceIdInboxRoute: typeof WWorkspaceIdInboxRoute
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdCChannelIdRoute: typeof WWorkspaceIdCChannelIdRoute
  WWorkspaceIdDChannelIdRoute: typeof WWorkspaceIdDChannelIdRoute
  WWorkspaceIdTThreadIdRoute: typeof WWorkspaceIdTThreadIdRoute
  WWorkspaceIdGGroupSlugChannelSlugRoute: typeof WWorkspaceIdGGroupSlugChannelSlugRoute
}

const WWorkspaceIdRouteChildren: WWorkspaceIdRouteChildren = {
  WWorkspaceIdChannelSlugRoute: WWorkspaceIdChannelSlugRoute,
  WWorkspaceIdEventsRoute: WWorkspaceIdEventsRoute,
  WWorkspaceIdInboxRoute: WWorkspaceIdInboxRoute,
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdCChannelIdRoute: WWorkspaceIdCChannelIdRoute,
  WWorkspaceIdDChannelIdRoute: WWorkspaceIdDChannelIdRoute,
  WWorkspaceIdTThreadIdRoute: WWorkspaceIdTThreadIdRoute,
  WWorkspaceIdGGroupSlugChannelSlugRoute:
    WWorkspaceIdGGroupSlugChannelSlugRoute,
}

const WWorkspaceIdRouteWithChildren = WWorkspaceIdRoute._addFileChildren(
  WWorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DocsRoute: DocsRoute,
  LocalRoute: LocalRouteWithChildren,
  WorkspacesRoute: WorkspacesRoute,
  ConnectTokenRoute: ConnectTokenRoute,
  InviteCodeRoute: InviteCodeRoute,
  WWorkspaceIdRoute: WWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
